# Generated by Django 4.1.7 on 2023-06-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=150)),
            ],
        ),
    ]
